# Generated by Django 4.1.13 on 2024-06-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IOLCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iol_model', models.CharField(max_length=50)),
                ('a_constant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ACD', models.DecimalField(decimal_places=2, max_digits=5)),
                ('K1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('K2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Target_refraction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iol_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('REFRACTION', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.patient')),
            ],
        ),
    ]
