# Generated by Django 4.1.13 on 2024-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_iolcalculation_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolcalculation',
            name='eye',
            field=models.CharField(choices=[('OD', 'Right Eye (OD)'), ('OS', 'Left Eye (OS)')], default='OD', max_length=2),
        ),
    ]
