# Generated by Django 4.1.13 on 2024-07-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_iolcalculation_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolcalculation',
            name='date_of_birth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='iol_calculations_dob', to='calculator.patient'),
        ),
        migrations.AlterField(
            model_name='iolcalculation',
            name='eye',
            field=models.CharField(choices=[('OD', 'Right Eye'), ('OS', 'Left Eye')], default='OD', max_length=2),
        ),
        migrations.AlterField(
            model_name='iolcalculation',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iol_calculations_patient', to='calculator.patient'),
        ),
    ]
