# Generated by Django 4.1.13 on 2024-07-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_iolcalculation_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iolcalculation',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='iolcalculation',
            name='patient_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculator.patient'),
        ),
    ]
